"""
Shared state between LangGraph nodes.

Required keys for Paid.ai (must be set by Agent 1):
- customer_id : external_id of the client in the Paid.ai dashboard (e.g. "acme_123")
- crisis_id   : unique UUID per run (generated by Agent 1, used as idempotency_key)
"""

from typing import TypedDict, Any


class GraphState(TypedDict, total=False):
    """Typed graph state."""

    # User input
    company_name: str

    # Paid.ai — required from Agent 1 onwards
    customer_id: str  # external_customer_id for Paid.ai
    crisis_id: str    # unique UUID per run (generated by Agent 1)

    # Agent 1 — each article: title, summary, url, content, pub_date,
    # authority_score, severity_score, recency_multiplier, exposure_score
    articles: list[dict[str, Any]]

    # Agent 2
    precedents: list[dict[str, Any]]
    global_lesson: str

    # Agent 3 — enriches each article with reach_estimate, churn_risk_percent, value_at_risk
    total_var_impact: float  # sum of VaR across all articles
    estimated_financial_loss: float  # alias for Paid.ai (= total_var_impact)
    severity_score: int  # max severity among articles

    # Agent 4
    strategy_report: dict[str, Any]
    recommended_strategy_name: str
    drafts_generated: int

    # API costs per agent (for Paid.ai)
    agent2_api_cost_eur: float
    agent3_api_cost_eur: float
    agent4_api_cost_eur: float
