"""
Shared state between LangGraph nodes.

Required keys for Paid.ai (set from Agent 1):
- customer_id: external_id of the customer in Paid.ai dashboard (e.g. "acme_123")
- crisis_id: UUID of the crisis session (for idempotency_key)
"""

from typing import TypedDict, Any


class GraphState(TypedDict, total=False):
    """Typed state of the graph."""

    # User input
    company_name: str

    # Paid.ai — required from Agent 1
    customer_id: str  # external_customer_id Paid.ai
    crisis_id: str    # Unique UUID per run (generated by Agent 1)

    # Agent 1 — flat list for Agents 2, 3
    articles: list[dict[str, Any]]
    # Agent 1 — grouped by subject for frontend: subject, title, summary, article_count, articles
    subjects: list[dict[str, Any]]

    # Agent 2
    precedents: list[dict[str, Any]]
    global_lesson: str
    confidence: str  # "high", "medium", or "low" — how much to trust the precedents
    agent2_sources: list[dict[str, Any]]  # {url, title, phase} — sources found via Google Search grounding

    # Agent 3 — enriches each article with reach_estimate, churn_risk_percent, value_at_risk
    total_var_impact: float  # sum of VaR for all articles
    estimated_financial_loss: float  # alias for Paid.ai (= total_var_impact)
    severity_score: int  # max severity among articles

    # Agent 4
    strategy_report: dict[str, Any]
    recommended_strategy_name: str
    drafts_generated: int

    # API costs per agent (for Paid.ai)
    agent2_api_cost_eur: float
    agent3_api_cost_eur: float
    agent4_api_cost_eur: float
